// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKaqA5aoxJuW7VqHCZL5LeTttdKletTs0',
    appId: '1:290624273134:web:3938045c09c66b47e391ff',
    messagingSenderId: '290624273134',
    projectId: 'mynotes-del',
    authDomain: 'mynotes-del.firebaseapp.com',
    storageBucket: 'mynotes-del.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5OGrl_Vuz5Vuq2rhCPHh8ffxw6EVOSAQ',
    appId: '1:290624273134:android:1794bdd2035d43d1e391ff',
    messagingSenderId: '290624273134',
    projectId: 'mynotes-del',
    storageBucket: 'mynotes-del.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQBDbow3dpxSZdNtG0F0v3jzRRQns3aTs',
    appId: '1:290624273134:ios:c25d9ef121b2dbdee391ff',
    messagingSenderId: '290624273134',
    projectId: 'mynotes-del',
    storageBucket: 'mynotes-del.appspot.com',
    iosBundleId: 'com.delphstuffs.myfirstnote',
  );
}
